### ISSUE TITLE
Meeting with Umesh -  Students Events Tracker on IOS and Andriod

### ISSUE THREAD

**Issue by chiranjeevichiru** [edwisely-ai/Relationship-Management#255]
- Events Tracker @Umesh Team is working on it
- by 15-06-2021 EOD, @umesh will give an update and gonna explain how the events are working with small set of events and somewhere in this week surely they are gonna close the Task.
- Testing will be done on Staging APK. and can compare the events on Amplitude(existing).

clarifications:

1. time spent is not inherent for every event it should be coded. so for events with time spent parameter, they will do it.
2. Umesh Team will integrate Amplitude with Code and show how events are working on Amplitude

Dependencies: 

1. need to share Amplitude IDs for Testing Purpose
2. creating Amplitude staging project 
3. adding User parameters, @Prahalya19 

@tudims  FYI

**Comment by Prahalya19** [comment]
@chiranjeevichiru, @tudims : Added the user parameters in API response
