### ISSUE TITLE
Issues in Unit-1 of AIDS

### ISSUE THREAD

**Issue by chiranjeevichiru** [edwisely-ai/Relationship-Management#338]
No Topics while adding questions for below subjects
 1. Introduction to Data science
 2. Digital Principles and Computer architecture

informed to @RAJASEKHAR36 

@Prahalya19 for your information

**Comment by RAJASEKHAR36** [comment]
@chiranjeevichiru 
1.The unit-1 for Introduction to Data science is already added and content is reflecting in the app.
2.The Topics are adding in the Digital Principles and Computer architecture,It will complete by 2:30 PM.
